# @package _global_
defaults:
  - _self_
  - data: default
  - model: lgbm
  - train: default
  - optuna: default
  - wandb: default

# Hydra output dir (runs are created under this folder)
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
